### ISSUE TITLE
overlay events

### ISSUE THREAD

**Issue by matti** [cavalle/chrome_remote#4]
with
`chrome.on "Overlay.inspectNodeRequested" do ...`

I have to 

```
loop do
  chrome.send_cmd "Overlay.enable"
  sleep 0.1
end
```

to get the events firing, is this a bug in this gem or is it just how the devtools protocol works?

**Comment by cavalle** [comment]
I'm not familiar with the `Overlay` domain, and I don't know if there's anything special about that particular event, but usually, in your script, you need to first enable the events:

```ruby
chrome.send_cmd "Overlay.enabled"
```

Then subscribe to the event you're interested in

```ruby
chrome.on "Overlay.inspectNodeRequested" do ...
```

And finally keep waiting until indefinitely (with `listen`) or until something happens (with `listen_until`).

You can check the README for examples.

For the moment, I'm closing the issue as we have no evidence there's anything wrong with the gem. If you find out anything else, please comment.
